// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.6.1.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides ++= {
  if (!(sbtLockHashIsUpToDate in ThisBuild).value && sbtLockIgnoreOverridesOnStaleHash.value) {
    Seq.empty
  } else {
    Seq(
      "co.fs2" % "fs2-core_2.13" % "3.0.4",
      "co.fs2" % "fs2-io_2.13" % "3.0.4",
      "com.comcast" % "ip4s-core_2.13" % "3.0.3",
      "com.fasterxml.jackson.core" % "jackson-annotations" % "2.12.3",
      "com.fasterxml.jackson.core" % "jackson-core" % "2.12.3",
      "com.fasterxml.jackson.core" % "jackson-databind" % "2.12.3",
      "com.fasterxml.jackson.dataformat" % "jackson-dataformat-yaml" % "2.12.3",
      "com.google.protobuf" % "protobuf-java" % "3.15.8",
      "com.olegpy" % "meow-mtl-effects_2.13" % "0.4.1",
      "com.thesamet.scalapb" % "lenses_2.13" % "0.11.3",
      "com.thesamet.scalapb" % "scalapb-runtime_2.13" % "0.11.3",
      "com.twitter" % "hpack" % "1.0.2",
      "io.circe" % "circe-core_2.13" % "0.14.1",
      "io.circe" % "circe-jawn_2.13" % "0.14.1",
      "io.circe" % "circe-numbers_2.13" % "0.14.1",
      "io.circe" % "circe-parser_2.13" % "0.14.1",
      "org.apache.logging.log4j" % "log4j-api" % "2.14.1",
      "org.apache.logging.log4j" % "log4j-core" % "2.14.1",
      "org.apache.logging.log4j" % "log4j-slf4j-impl" % "2.14.1",
      "org.http4s" % "blaze-core_2.13" % "0.15.1",
      "org.http4s" % "blaze-http_2.13" % "0.15.1",
      "org.http4s" % "http4s-blaze-core_2.13" % "0.23.0-RC1",
      "org.http4s" % "http4s-blaze-server_2.13" % "0.23.0-RC1",
      "org.http4s" % "http4s-core_2.13" % "0.23.0-RC1",
      "org.http4s" % "http4s-dsl_2.13" % "0.23.0-RC1",
      "org.http4s" % "http4s-server_2.13" % "0.23.0-RC1",
      "org.log4s" % "log4s_2.13" % "1.10.0",
      "org.scala-lang.modules" % "scala-collection-compat_2.13" % "2.4.4",
      "org.scodec" % "scodec-bits_2.13" % "1.1.27",
      "org.slf4j" % "slf4j-api" % "1.7.30",
      "org.typelevel" % "case-insensitive_2.13" % "1.1.4",
      "org.typelevel" % "cats-core_2.13" % "2.6.1",
      "org.typelevel" % "cats-effect-kernel_2.13" % "3.1.1",
      "org.typelevel" % "cats-effect-std_2.13" % "3.1.1",
      "org.typelevel" % "cats-effect_2.13" % "3.1.1",
      "org.typelevel" % "cats-kernel_2.13" % "2.6.1",
      "org.typelevel" % "cats-mtl-core_2.13" % "0.7.1",
      "org.typelevel" % "cats-mtl_2.13" % "1.2.1",
      "org.typelevel" % "cats-parse_2.13" % "0.3.4",
      "org.typelevel" % "jawn-parser_2.13" % "1.1.2",
      "org.typelevel" % "literally_2.13" % "1.0.2",
      "org.typelevel" % "log4cats-core_2.13" % "2.1.1",
      "org.typelevel" % "log4cats-slf4j_2.13" % "2.1.1",
      "org.typelevel" % "simulacrum-scalafix-annotations_2.13" % "0.5.4",
      "org.typelevel" % "simulacrum_2.13" % "1.0.1",
      "org.typelevel" % "vault_2.13" % "3.0.3",
      "org.yaml" % "snakeyaml" % "1.27"
    )
  }
}
// LIBRARY_DEPENDENCIES_HASH dc4867df47cd987b26d74721ba319775e7adfc25
