version: "2.1"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka-broker:
    image: wurstmeister/kafka:2.12-2.0.1
    ports:
      - "9092:9092"
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_CREATE_TOPICS: "names:1:1,greets:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  master:
    image: apache/flink-statefun:3.0.0-java11
    expose:
      - "6123"
    depends_on:
      - kafka-broker
    ports:
      - "8081:8081"
    environment:
      - ROLE=master
      - MASTER_HOST=master
    volumes:
      - ./checkpoint-dir:/checkpoint-dir
      - ./module.yaml:/opt/statefun/modules/greeter/module.yaml

  worker:
    image: apache/flink-statefun:3.0.0-java11
    expose:
      - "6121"
      - "6122"
    depends_on:
      - master
      - kafka-broker
    environment:
      - ROLE=worker
      - MASTER_HOST=master
    links:
      - "master:master"
      - "kafka-broker:kafka-broker"
    volumes:
      - ./checkpoint-dir:/checkpoint-dir
      - ./module.yaml:/opt/statefun/modules/greeter/module.yaml

  scala-worker:
    build:
      context: worker
      dockerfile: Dockerfile
    expose:
      - "8080"

  event-generator:
    build:
      context: generator
      dockerfile: Dockerfile
    depends_on:
      - kafka-broker
